"""Webhook routes for Apple Health Shortcut integration.

Route 1 — POST /api/v1/webhook/apple-health/{token}
    Catches the massive JSON payload POSTed by the iOS Shortcut after the
    patient syncs their Apple Health data.  Updates the MongoDB
    ``appointments`` document that matches the given *token*, setting the
    ``biometrics`` field to the received payload and a boolean flag
    ``biometrics_received = True`` so the frontend polling endpoint can
    detect completion.

Route 2 — GET /api/v1/intake/{token}/status
    Lightweight polling endpoint consumed by the Next.js intake form.
    Returns ``{"biometrics_received": true}`` once the webhook has fired,
    or ``{"biometrics_received": false}`` while the patient hasn't synced
    yet.
"""

from __future__ import annotations

import logging
from typing import Any, Dict

from fastapi import APIRouter, HTTPException, Request

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1", tags=["webhook"])


@router.post("/webhook/apple-health/{token}")
async def receive_apple_health(
    token: str,
    payload: Dict[str, Any],
    request: Request,
):
    """Receive the Apple Health payload from the iOS Shortcut.

    The iOS Shortcut pulls HealthKit data and POSTs it here, tagged with the
    patient's unique intake *token*.  We persist the raw payload on the
    matching ``appointments`` document and flip ``biometrics_received`` so the
    frontend can detect the data has arrived.

    Path Parameters:
        token: Unique appointment / intake token identifying the patient
               session.

    Request Body:
        Arbitrary JSON dict generated by the Apple Shortcut containing
        HealthKit biometric data.
    """
    db = request.app.state.mongo_client[request.app.state.db_name]
    appointments = db.appointments

    # Validate the appointment exists
    appointment = appointments.find_one({"form_token": token})
    if not appointment:
        raise HTTPException(
            status_code=404,
            detail="Appointment not found for the provided token.",
        )

    # Persist biometrics and flip the received flag using the $set operator
    appointments.update_one(
        {"form_token": token},
        {
            "$set": {
                "biometrics": payload,
                "biometrics_received": True,
            },
        },
    )

    logger.info("Biometric payload received for token %s", token)

    return {"status": "received", "token": token}


@router.get("/intake/{token}/status")
async def intake_status(token: str, request: Request):
    """Lightweight status-check endpoint polled by the frontend.

    The Next.js intake form hits this every ~2 seconds while the patient is
    scanning the QR code / running the iOS Shortcut.  Once the webhook fires
    and sets ``biometrics_received = True``, this endpoint reflects that so
    the frontend can auto-advance to the success step.

    Path Parameters:
        token: Unique appointment / intake token.
    """
    db = request.app.state.mongo_client[request.app.state.db_name]
    appointments = db.appointments

    appointment = appointments.find_one({"form_token": token})
    if not appointment:
        raise HTTPException(
            status_code=404,
            detail="Appointment not found for the provided token.",
        )

    return {
        "biometrics_received": bool(appointment.get("biometrics_received", False)),
        "already_submitted": appointment.get("status") == "completed",
    }
